<?php

return [
    'baseUrl'  => 'http://localhost/siron',
    'database' => [
        'host'     => 'localhost',
        'username' => 'root',
        'passwd'   => '',
        'dbname'   => 'SIRON',
        'mapper'   => 'PDO', // can be MYSQLI
    ],
    'baseDir'  => __DIR__,
    'debug'    =>  true,
    'max_upload_time' => '1800', // in seconds
    'disable_security_login' => false, // true to use the application without login

    'MenuLabels' => [
        'Upload' => 'Upload',
        'AlertPerStatus' => 'Status',
        'HitPerScore' => 'Score',
        'Category' => 'Scenario & category',
        'SAR' => 'Scenarios & SAR',
        'Risk' => 'Risk Country',
        'Transaction' => 'Transaction',
        'Scenario' => 'Active Scenarios',
        'ThresholdsperC' => 'Thresholds cat & scenario',
        'ThresholdsperCaI' => 'Thresholds cat',
        'Alert'  => 'Treatment Delay',
        'Update' => 'Last updates',
    ],
    'pagesMenu' => [
        'Upload' => 'Upload',
        'AlertPerStatus' => 'AlertPerStatus',
        'AlertPerStatus2' => 'AlertPerStatus',
        'HitPerScore' => 'HitPerScore',
        'HitPerScore2' => 'HitPerScore',
        'Category' => 'Category',
        'SAR' => 'SAR',
        'Risk' => 'Risk',
        'Transaction' => 'Transaction',
        'Scenario' => 'Scenario',
        'Category2' => 'Category',
        'Category3' => 'Category',
        'ThresholdsperC' => 'ThresholdsperC',
        'ThresholdsperCaI' => 'ThresholdsperCaI',
        'Alert' => 'Alert',
        'Update' => 'Update',
        'Update2' => 'Update',
        'Update3' => 'Update',
        'Update4' => 'Update',
    ],

    'BackMenu' => [
        'Configuration' => [
            'label' => 'Configurations',
        ],
    ],

    'alertFileRegex' => '`ALERTS.*\.CSV$`',
    'alertFieldsColumn' => [
        'period' => 'PERIOD',
        'subsidiary' => 'SUBSIDIARY',
        'bankid' => 'BANKID',
        'scoringdate' => 'SCORINGDATE',
        'lastentrydate' => 'LASTENTRYDATE',
        'hitid' => 'HITID',
        'customerid' => 'CUSTOMERID',
        'category_id' => 'CATEGORY_ID',     /////////////////////////////////////////////////////////////
        'category_name' => 'CATEGORY_NAME', /////////////////////////////////////////////////////////////
        'firsttreatment' => 'FIRSTTREATMENT',
        'lasttreatment' => 'LASTTREATMENT',
        'alert_status' => 'ALERT_STATUS',
        'no_of_days' => 'NO_OF_DAYS',
        'monitoring_yn' => 'MONITORING_YN',
        'monitoring_type' => 'MONITORING_TYPE',
        'reminder_yn' => 'REMINDER_YN',
        'lastfeedback' => 'LASTFEEDBACK',
        'feedback_author' => 'FEEDBACK_AUTHOR',
        'total_score' => 'TOTAL_SCORE',
        'no_of_scenarios' => 'NO_OF_SCENARIOS',
        'ass_scenario_1' => 'ASS_SCENARIO(1)',
        'ass_scenario_2' => 'ASS_SCENARIO(2)',
        'ass_scenario_3' => 'ASS_SCENARIO(3)',
        'ass_scenario_4' => 'ASS_SCENARIO(4)',
        'ass_scenario_5' => 'ASS_SCENARIO(5)',
        'ass_scenario_6' => 'ASS_SCENARIO(6)',
        'ass_scenario_7' => 'ASS_SCENARIO(7)',
        'ass_scenario_8' => 'ASS_SCENARIO(8)',
        'ass_scenario_9' => 'ASS_SCENARIO(9)',
        'ass_scenario_10' => 'ASS_SCENARIO(10)',
        'ass_scenario_11' => 'ASS_SCENARIO(11)',
        'ass_scenario_12' => 'ASS_SCENARIO(12)',
        'ass_scenario_13' => 'ASS_SCENARIO(13)',
        'ass_scenario_14' => 'ASS_SCENARIO(14)',
        'ass_scenario_15' => 'ASS_SCENARIO(15)',
        'ass_scenario_16' => 'ASS_SCENARIO(16)',
        'ass_scenario_17' => 'ASS_SCENARIO(17)',
        'ass_scenario_18' => 'ASS_SCENARIO(18)',
        'ass_scenario_19' => 'ASS_SCENARIO(19)',
        'ass_scenario_20' => 'ASS_SCENARIO(20)',
        'ass_scenario_21' => 'ASS_SCENARIO(21)',
        'ass_scenario_22' => 'ASS_SCENARIO(22)',
        'ass_scenario_23' => 'ASS_SCENARIO(23)',
        'ass_scenario_24' => 'ASS_SCENARIO(24)',
        'ass_scenario_25' => 'ASS_SCENARIO(25)',
        'ass_scenario_26' => 'ASS_SCENARIO(26)',
        'ass_scenario_27' => 'ASS_SCENARIO(27)',
        'ass_scenario_28' => 'ASS_SCENARIO(28)',
        'ass_scenario_29' => 'ASS_SCENARIO(29)',
        'ass_scenario_30' => 'ASS_SCENARIO(30)',
        'ass_scenario_31' => 'ASS_SCENARIO(31)',
        'ass_scenario_32' => 'ASS_SCENARIO(32)',
        'ass_scenario_33' => 'ASS_SCENARIO(33)',
        'ass_scenario_34' => 'ASS_SCENARIO(34)',
        'ass_scenario_35' => 'ASS_SCENARIO(35)',
        'ass_scenario_36' => 'ASS_SCENARIO(36)',
        'ass_scenario_37' => 'ASS_SCENARIO(37)',
        'ass_scenario_38' => 'ASS_SCENARIO(38)',
        'ass_scenario_39' => 'ASS_SCENARIO(39)',
        'ass_scenario_40' => 'ASS_SCENARIO(40)',
        'ass_scenario_41' => 'ASS_SCENARIO(41)',
        'ass_scenario_42' => 'ASS_SCENARIO(42)',
        'ass_scenario_43' => 'ASS_SCENARIO(43)',
        'ass_scenario_44' => 'ASS_SCENARIO(44)',
        'ass_scenario_45' => 'ASS_SCENARIO(45)',
        'ass_scenario_46' => 'ASS_SCENARIO(46)',
        'ass_scenario_47' => 'ASS_SCENARIO(47)',
        'ass_scenario_48' => 'ASS_SCENARIO(48)',
        'ass_scenario_49' => 'ASS_SCENARIO(49)',
        'ass_scenario_50' => 'ASS_SCENARIO(50)',
    ],

    'freqHitsCategoryFileRegex' => '`FREQ_OF_HITS_PER_CUSTOMER_CATEGORY\.CSV$`',
    'freqHitsCategoryFieldsColumn' => [
        'period' => 'PERIOD',
        'subsidiary' => 'SUBSIDIARY',
        'bankid' => 'BANKID',
        'category_id' => 'CATEGORY_ID',
        'no_of_hits' => 'NO_OF_HITS',
        'frequency' => 'FREQUENCY',
    ],

    'freqHitsScenarioFileRegex' => '`FREQ_OF_HITS_PER_SCENARIO\.CSV$`',
    'freqHitsScenarioFieldsColumn' => [
        'period' => 'PERIOD',
        'subsidiary' => 'SUBSIDIARY',
        'bankid' => 'BANKID',
        'scenario' => 'SCENARIO',
        'no_of_hits' => 'NO_OF_HITS',
        'frequency' => 'FREQUENCY',
    ],

    'seuilFileRegex' => '`SCENARIO_VARIABLES\.CSV$`',
    'seuilFieldsColumn' => [
        'period' => 'PERIOD',
        'subsidiary' => 'SUBSIDIARY',
        'bankid' => 'BANKID',
        'UPDATE_FLAG' => 'UPDATE_FLAG',
        'R_VALID_FROM' => 'R_VALID_FROM',
        'R_VALID_TO' => 'R_VALID_TO',
        'CREATED_BY' => 'CREATED_BY',
        'DELETED_BY' => 'DELETED_BY',
        'STATUS' => 'STATUS',
        'VAR_ID' => 'VAR_ID',
        'VAR_EXT_NAME' => 'VAR_EXT_NAME',
        'VAR_INT_NAME1' => 'VAR_INT_NAME1',
        'VAR_INT_NAME2' => 'VAR_INT_NAME2',
        'VAR_BASIS' => 'VAR_BASIS',
        'VAR_DATATYPE' => 'VAR_DATATYPE',
        'VAR_COMMENT' => 'VAR_COMMENT',
        'VAR_SYNTAX' => 'VAR_SYNTAX',
//      'VAR_SYNTAX_EUR' => '',
        'VAR_EXT_NAME_COMOBJ' => 'VAR_EXT_NAME_COMOBJ',
        'VAR_OPERATOR' => 'VAR_OPERATOR',
        'VAR_LIST' => 'VAR_LIST',
    ],
    'seuilGlobalCategories' => [
        'ALL' => 'ALL',
        'AFF' => 'AFF',
        'ASS' => 'ASS',
        'BNK' => 'BNK',
        'EMP' => 'EMP',
        'FCO' => 'FCO',
        'IND' => 'IND',
        'LAS' => 'LAS',
        'LCO' => 'LCO',
        'MCO' => 'MCO',
        'NSG' => 'NSG',
        'PEP' => 'PEP',
        'PRO' => 'PRO',
        'PRV' => 'PRV',
        'SCO' => 'SCO',
        'SOV' => 'SOV',
        'VSE' => 'VSE',
    ],
    'scenarioVariables' => [
        'Account' => 'Account',
        'Curr'    => 'Curr',
        'Loan'    => 'Loan',
        'freq'    => 'freq',
        'Max'     => 'Max',
        'Min'     => 'Min',
        '1Min'    => '1Min',
        'Nb'      => 'Nb',
        'Other'   => 'Other',
        'Sum'     => 'Sum',
        'TOTAL'   => 'TOTAL',
        'X'       => 'X',
    ],

    'rateFileRegex' => '`CONVERSION\.xls$`',
    'rateFieldsColumn' => [
        'subsidiary'        => 'SUBSIDIARY',
        'pays'              => 'COUNTRY',
        'devise_locale'     => 'DEVISE LOCALE',
        'devise_destination'=> 'DEVISE DEST',
        'taux'              => 'RATE',
        'date'              => 'DATE',
    ],

    'categoryFileRegex' => '`CATEGORY.*CLIENTS\.csv$`',
    'categoryFieldsColumn' => [
        'period'        => 'PERIOD',
        'subsidiary'    => 'SUBSIDIARY',
        'bankid'        => 'BANKID',
        'update_flag'   => 'UPDATE_FLAG',
        'r_valid_from'  => 'R_VALID_FROM',
        'r_valid_to'    => 'R_VALID_TO',
        'created_by'    => 'CREATED_BY',
        'deleted_by'    => 'DELETED_BY',
        'status'        => 'STATUS',
        'valid_from'    => 'VALID_FROM',
        'valid_to'      => 'VALID_TO',
        'category_id'   => 'CATEGORY_ID',
        'category_name' => 'CATEGORY_NAME',
        'risk_class'    => 'RISK_CLASS',
        'category_definition' => 'CATEGORY_DEFINITION',
        'syntax' => 'SYNTAX',
    ],

    'scenarioFileRegex' => '`SCENARIOS\.csv$`',
    'scenarioFieldsColumn' => [
        'period' => 'PERIOD',
        'subsidiary' => 'SUBSIDIARY',
        'bankid' => 'BANKID',
        'update_flag' => 'UPDATE_FLAG',
        'r_valid_from' => 'R_VALID_FROM',
        'r_valid_to' => 'R_VALID_TO',
        'created_by' => 'CREATED_BY',
        'deleted_by' => 'DELETED_BY',
        'valid_from' => 'VALID_FROM',
        'valid_to' => 'VALID_TO',
        'status' => 'STATUS',
        'scen_id' => 'SCEN_ID',
        'scen_score' => 'SCEN_SCORE',
        'scen_name' => 'SCEN_NAME',
        'scen_comment' => 'SCEN_COMMENT',
        'scen_level' => 'SCEN_LEVEL',
        'scen_basis' => 'SCEN_BASIS',
        'category_name' => 'CATEGORY_NAME',
        'scen_cat_syntax' => 'SCEN_CAT_SYNTAX',
        'addcriteria_comobj' => 'ADDCRITERIA_COMOBJ',
        'addcriteria_level_c' => 'ADDCRITERIA_LEVEL_C',
        'addcriteria_level_b' => 'ADDCRITERIA_LEVEL_B',
        'addcriteria_level_a' => 'ADDCRITERIA_LEVEL_A',
        'addcriteria_optor_c' => 'ADDCRITERIA_OPTOR_C',
        'addcriteria_optor_b' => 'ADDCRITERIA_OPTOR_B',
        'addcriteria_optor_a' => 'ADDCRITERIA_OPTOR_A',
        'addcriteria_valfrom_c' => 'ADDCRITERIA_VALFR_C',
        'addcriteria_valfrom_b' => 'ADDCRITERIA_VALFR_B',
        'addcriteria_valfrom_a' => 'ADDCRITERIA_VALFR_A',
        'addcriteria_valto_c' => 'ADDCRITERIA_VALTO_C',
        'addcriteria_valto_b' => 'ADDCRITERIA_VALTO_B',
        'addcriteria_valto_a' => 'ADDCRITERIA_VALTO_A',
        'scen_cat_comment' => 'SCEN_CAT_COMMENT',
    ],

    'riskCountriesFileRegex' => '`risk_countries\.csv$`',
    'riskCountriesFieldsColumn' => [
        'bankid' => 'BANKID',
        'subsidiary' => 'SUBSIDIARY',
        'period' => 'PERIOD',
        'update_flag' => 'UPDATE_FLAG',
        'r_valid_from' => 'R_VALID_FROM',
        'r_valid_to' => 'R_VALID_TO',
        'created_by' => 'CREATED_BY',
        'deleted_by' => 'DELETED_BY',
        'country_iso' => 'COUNTRY_ISO',
        'country_name' => 'COUNTRY_NAME',
        'country_risk_weight' => 'COUNTRY_RISK_WEIGHT',
        'country_regulation' => 'COUNTRY_REGULATION',
        'comment' => 'COMMENT',
    ],

    'transactionFileRegex' => '`TRANS_NUMB_PER_CASH_CAT\.CSV$`',
    'transactionFieldsColumn' => [
        'start_month' => 'START_MONTH',
        'prev_month' => 'PREV_MONTH',
        'bankid' => 'INSTITUT',
        'category_id' => 'CATGORY_ID',
        'category_name' => 'CATEGORY_NAME',
        'numb_trans_all' => 'NUMB_TRANS_ALL',
        'numb_trans_cash' => 'NUMB_TRANS_CASH',
        'numb_trans_non_cash' => 'NUMB_TRANS_NON_CASH',
    ],

    'deviseFileRegex'  => '`n001005.*\.xlsx$`',
    'deviseDateFormat' => 'DD-MM-YYYY',
    'deviseFieldsColumn' => [
        'date_devise'  => 'DATE DU COURS DE CHANGE (format du filtre : AAAA-MM-JJ)',
        'code_devise'  => 'Code Devise',
        'code_devise1' => 'Code Devise pour 1',
        'label_fr' => 'Libellé fr. de la Devise',
        'label_en' => 'Libellé ang. de la Devise',
        'value'    => 'Valeur du Cours de Change',
        'country_label_fr' => 'Libellé fr. du Pays de la Devise',
        'country_label_en' => 'Libellé ang. du Pays de la Devise',
    ],
];
